development:
  adapter: postgresql
  encoding: unicode
  database: kiino_player_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: kiino_player_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: kiino_player_production
  pool: 5
